### ISSUE TITLE
DIS Pantalla de login [24/06]

### ISSUE THREAD

**Issue by eumati** [eumati/residencia_2015#6]
- Diseñar una pantalla nueva de login
 * los estilos de esta pnatalla no estan en base a stylus, hay que generar un .styl en la carpta "login/css" para los nuevos estilos
 * Hay que cambiar las imagenes y logos que se ven en la pantalla de login, por imagenes de contbilidad y el logo de la empresa

**Comment by jorges85** [comment]
Cual seria el nuevo logo ?
